import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# TalentSync AI - Resume Parser & Experience Validator\n",
    "\n",
    "This notebook implements the resume parsing layer. It satisfies the following requirements:\n",
    "- Extracts only four sections: **SKILLS**, **EXPERIENCE**, **PROJECTS**, and **EDUCATION**.\n",
    "- Handles header synonyms case-insensitively.\n",
    "- Enforces the **Critical Section Isolation Rule** to avoid cross-contamination.\n",
    "- Enforces the **Experience Validation Rule**: checks if job role, company, and duration exist in experience entries. Otherwise sets Experience Score = 0.\n",
    "- Detects and rejects scanned or image-only PDFs, returning a user-friendly error message."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import re\n",
    "import json\n",
    "import pdfplumber\n",
    "import pandas as pd\n",
    "\n",
    "print(\"Libraries imported successfully!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Resume Parser Implementation\n",
    "\n",
    "We implement the parser code here. We will use a regex search to identify header start/end character offsets, sort them, slice the text into isolated regions, and parse each region."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Header regex dictionary\n",
    "HEADERS_REGEX = {\n",
    "    'SKILLS': re.compile(r'^\\s*[-*•]?\\s*(skills|technical\\s+skills|core\\s+skills)\\s*:?\\s*$', re.IGNORECASE | re.MULTILINE),\n",
    "    'EXPERIENCE': re.compile(r'^\\s*[-*•]?\\s*(experience|work\\s+experience|professional\\s+experience|internships)\\s*:?\\s*$', re.IGNORECASE | re.MULTILINE),\n",
    "    'PROJECTS': re.compile(r'^\\s*[-*•]?\\s*(projects|academic\\s+projects|personal\\s+projects)\\s*:?\\s*$', re.IGNORECASE | re.MULTILINE),\n",
    "    'EDUCATION': re.compile(r'^\\s*[-*•]?\\s*(education|academic\\s+background)\\s*:?\\s*$', re.IGNORECASE | re.MULTILINE)\n",
    "}\n",
    "\n",
    "def extract_text_from_pdf(pdf_path):\n",
    "    try:\n",
    "        with pdfplumber.open(pdf_path) as pdf:\n",
    "            text = \"\"\n",
    "            for page in pdf.pages:\n",
    "                page_text = page.extract_text()\n",
    "                if page_text:\n",
    "                    text += page_text + \"\\n\"\n",
    "            return text\n",
    "    except Exception as e:\n",
    "        print(f\"Error reading PDF {pdf_path}: {e}\")\n",
    "        return None\n",
    "\n",
    "def validate_experience_entry(entry_text):\n",
    "    \"\"\"\n",
    "    Checks if an experience entry contains:\n",
    "    1. Job Role\n",
    "    2. Company/organization\n",
    "    3. Duration\n",
    "    \"\"\"\n",
    "    role_pattern = re.compile(r'(engineer|developer|scientist|manager|intern|analyst|programmer|lead|specialist|architect|coordinator|designer)', re.IGNORECASE)\n",
    "    company_pattern = re.compile(r'(google|microsoft|meta|amazon|netflix|apple|stripe|uber|airbnb|salesforce|atlassian|slack|technologies|solutions|labs|corp|inc|llc|co\\b|global|tech|group|systems|enterprise|ventures)', re.IGNORECASE)\n",
    "    # Matches common date range formats like \"June 2025 - August 2025\", \"Jan 2022 - Present\", \"2020 - 2022\"\n",
    "    duration_pattern = re.compile(r'((?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\\s*\\d{4}\\s*(?:-|–|—|to)\\s*(?:present|(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\\s*\\d{4})|\\d{4}\\s*(?:-|–|—|to)\\s*(?:\\d{4}|present))', re.IGNORECASE)\n",
    "    \n",
    "    has_role = bool(role_pattern.search(entry_text))\n",
    "    has_company = bool(company_pattern.search(entry_text))\n",
    "    has_duration = bool(duration_pattern.search(entry_text))\n",
    "    \n",
    "    return has_role and has_company and has_duration\n",
    "\n",
    "def parse_resume(pdf_path):\n",
    "    text = extract_text_from_pdf(pdf_path)\n",
    "    \n",
    "    # Scanned PDF check\n",
    "    if not text or len(text.strip()) < 100:\n",
    "        return {\n",
    "            \"success\": False,\n",
    "            \"error\": \"Scanned or image-only PDF detected. Please upload a text-based PDF resume.\"\n",
    "        }\n",
    "    \n",
    "    # Find all header matches\n",
    "    matches = []\n",
    "    for section, regex in HEADERS_REGEX.items():\n",
    "        for m in regex.finditer(text):\n",
    "            matches.append({\n",
    "                'section': section,\n",
    "                'start': m.start(),\n",
    "                'end': m.end(),\n",
    "                'line': m.group(0)\n",
    "            })\n",
    "            \n",
    "    # Sort matches by start index to isolate sections\n",
    "    matches = sorted(matches, key=lambda x: x['start'])\n",
    "    \n",
    "    parsed_sections = {\n",
    "        'SKILLS': '',\n",
    "        'EXPERIENCE': '',\n",
    "        'PROJECTS': '',\n",
    "        'EDUCATION': ''\n",
    "    }\n",
    "    \n",
    "    for i, m in enumerate(matches):\n",
    "        start_idx = m['end']\n",
    "        # The section content goes until the start of the next section header\n",
    "        end_idx = matches[i+1]['start'] if i + 1 < len(matches) else len(text)\n",
    "        \n",
    "        section_text = text[start_idx:end_idx].strip()\n",
    "        # Store only if we don't already have text (keep first match or append if multiple)\n",
    "        if parsed_sections[m['section']]:\n",
    "            parsed_sections[m['section']] += \"\\n\" + section_text\n",
    "        else:\n",
    "            parsed_sections[m['section']] = section_text\n",
    "            \n",
    "    # Validate Experience Section\n",
    "    exp_text = parsed_sections['EXPERIENCE'].strip()\n",
    "    is_exp_valid = False\n",
    "    if exp_text:\n",
    "        # Split by paragraph to check individual jobs\n",
    "        entries = [e.strip() for e in exp_text.split('\\n\\n') if e.strip()]\n",
    "        for entry in entries:\n",
    "            if validate_experience_entry(entry):\n",
    "                is_exp_valid = True\n",
    "                break\n",
    "                \n",
    "    parsed_sections['EXPERIENCE_VALID'] = is_exp_valid\n",
    "    \n",
    "    return {\n",
    "        \"success\": True,\n",
    "        \"data\": parsed_sections\n",
    "    }"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Testing the Parser on Synthetic Data\n",
    "\n",
    "We run the parser across all 205 generated PDF resumes to check the parsing rate and validation flags."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "results = []\n",
    "for idx in range(1, 206):\n",
    "    path = f\"../data/resumes/resume_{idx:03d}.pdf\"\n",
    "    parsed = parse_resume(path)\n",
    "    results.append({\n",
    "        \"id\": idx,\n",
    "        \"filename\": f\"resume_{idx:03d}.pdf\",\n",
    "        \"success\": parsed[\"success\"],\n",
    "        \"error\": parsed.get(\"error\", None),\n",
    "        \"skills_extracted\": len(parsed.get(\"data\", {}).get(\"SKILLS\", \"\")) > 0 if parsed[\"success\"] else False,\n",
    "        \"experience_valid\": parsed.get(\"data\", {}).get(\"EXPERIENCE_VALID\", False) if parsed[\"success\"] else False,\n",
    "        \"education_extracted\": len(parsed.get(\"data\", {}).get(\"EDUCATION\", \"\")) > 0 if parsed[\"success\"] else False\n",
    "    })\n",
    "\n",
    "df = pd.DataFrame(results)\n",
    "print(df.tail(15))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Analysis & Visualizations of Parsing Results"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Success Rate:\", df[\"success\"].mean() * 100, \"%\")\n",
    "print(\"Experience Validation Rate (of successful parses):\", df[df[\"success\"]][\"experience_valid\"].mean() * 100, \"%\")\n",
    "print(\"Rejection Count:\", df[~df[\"success\"]].shape[0])"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Exporting the Parser Module\n",
    "\n",
    "We write the core parsing functions to `../app/parser.py` so that they can be loaded by the web app."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "parser_code = \"\"\"import re\n",
    "import pdfplumber\n",
    "\n",
    "# Header regex dictionary\n",
    "HEADERS_REGEX = {\n",
    "    'SKILLS': re.compile(r'^\\\\s*[-*•]?\\\\s*(skills|technical\\\\s+skills|core\\\\s+skills)\\\\s*:?\\\\s*$', re.IGNORECASE | re.MULTILINE),\n",
    "    'EXPERIENCE': re.compile(r'^\\\\s*[-*•]?\\\\s*(experience|work\\\\s+experience|professional\\\\s+experience|internships)\\\\s*:?\\\\s*$', re.IGNORECASE | re.MULTILINE),\n",
    "    'PROJECTS': re.compile(r'^\\\\s*[-*•]?\\\\s*(projects|academic\\\\s+projects|personal\\\\s+projects)\\\\s*:?\\\\s*$', re.IGNORECASE | re.MULTILINE),\n",
    "    'EDUCATION': re.compile(r'^\\\\s*[-*•]?\\\\s*(education|academic\\\\s+background)\\\\s*:?\\\\s*$', re.IGNORECASE | re.MULTILINE)\n",
    "}\n",
    "\n",
    "def extract_text_from_pdf(pdf_path):\n",
    "    try:\n",
    "        with pdfplumber.open(pdf_path) as pdf:\n",
    "            text = \"\"\n",
    "            for page in pdf.pages:\n",
    "                page_text = page.extract_text()\n",
    "                if page_text:\n",
    "                    text += page_text + \"\\\\n\"\n",
    "            return text\n",
    "    except Exception as e:\n",
    "        print(f\"Error reading PDF {pdf_path}: {e}\")\n",
    "        return None\n",
    "\n",
    "def validate_experience_entry(entry_text):\n",
    "    role_pattern = re.compile(r'(engineer|developer|scientist|manager|intern|analyst|programmer|lead|specialist|architect|coordinator|designer)', re.IGNORECASE)\n",
    "    company_pattern = re.compile(r'(google|microsoft|meta|amazon|netflix|apple|stripe|uber|airbnb|salesforce|atlassian|slack|technologies|solutions|labs|corp|inc|llc|co\\\\b|global|tech|group|systems|enterprise|ventures)', re.IGNORECASE)\n",
    "    duration_pattern = re.compile(r'((?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\\\\s*\\\\d{4}\\\\s*(?:-|–|—|to)\\\\s*(?:present|(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\\\\s*\\\\d{4})|\\\\d{4}\\\\s*(?:-|–|—|to)\\\\s*(?:\\\\d{4}|present))', re.IGNORECASE)\n",
    "    \n",
    "    has_role = bool(role_pattern.search(entry_text))\n",
    "    has_company = bool(company_pattern.search(entry_text))\n",
    "    has_duration = bool(duration_pattern.search(entry_text))\n",
    "    \n",
    "    return has_role and has_company and has_duration\n",
    "\n",
    "def parse_resume(pdf_path):\n",
    "    text = extract_text_from_pdf(pdf_path)\n",
    "    \n",
    "    if not text or len(text.strip()) < 100:\n",
    "        return {\n",
    "            \"success\": False,\n",
    "            \"error\": \"Scanned or image-only PDF detected. Please upload a text-based PDF resume.\"\n",
    "        }\n",
    "    \n",
    "    matches = []\n",
    "    for section, regex in HEADERS_REGEX.items():\n",
    "        for m in regex.finditer(text):\n",
    "            matches.append({\n",
    "                'section': section,\n",
    "                'start': m.start(),\n",
    "                'end': m.end(),\n",
    "                'line': m.group(0)\n",
    "            })\n",
    "            \n",
    "    matches = sorted(matches, key=lambda x: x['start'])\n",
    "    \n",
    "    parsed_sections = {\n",
    "        'SKILLS': '',\n",
    "        'EXPERIENCE': '',\n",
    "        'PROJECTS': '',\n",
    "        'EDUCATION': ''\n",
    "    }\n",
    "    \n",
    "    for i, m in enumerate(matches):\n",
    "        start_idx = m['end']\n",
    "        end_idx = matches[i+1]['start'] if i + 1 < len(matches) else len(text)\n",
    "        \n",
    "        section_text = text[start_idx:end_idx].strip()\n",
    "        if parsed_sections[m['section']]:\n",
    "            parsed_sections[m['section']] += \"\\\\n\" + section_text\n",
    "        else:\n",
    "            parsed_sections[m['section']] = section_text\n",
    "            \n",
    "    exp_text = parsed_sections['EXPERIENCE'].strip()\n",
    "    is_exp_valid = False\n",
    "    if exp_text:\n",
    "        entries = [e.strip() for e in exp_text.split('\\\\n\\\\n') if e.strip()]\n",
    "        for entry in entries:\n",
    "            if validate_experience_entry(entry):\n",
    "                is_exp_valid = True\n",
    "                break\n",
    "                \n",
    "    parsed_sections['EXPERIENCE_VALID'] = is_exp_valid\n",
    "    \n",
    "    return {\n",
    "        \"success\": True,\n",
    "        \"data\": parsed_sections\n",
    "    }\n",
    "\"\"\"\n",
    "\n",
    "with open('../app/parser.py', 'w', encoding='utf-8') as f:\n",
    "    f.write(parser_code.strip())\n",
    "print(\"app/parser.py written successfully!\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

with open('notebooks/resume_parser.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2)
print("resume_parser.ipynb written!")
