import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# TalentSync AI - Data Preprocessing & Synthesis\n",
    "\n",
    "This notebook generates a synthetic dataset of resumes and job descriptions to train and evaluate the resume matching platform. It satisfies the following requirements:\n",
    "- Generates at least **200 distinct resumes**.\n",
    "- Generates at least **50 job descriptions**.\n",
    "- Converts resumes to structured, text-based PDF files using `reportlab`.\n",
    "- Constructs train/test splits for the embedding models.\n",
    "- Evaluates and visualizes the dataset statistics."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import json\n",
    "import random\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from reportlab.lib.pagesizes import letter\n",
    "from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer\n",
    "from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle\n",
    "import pdfplumber\n",
    "\n",
    "# Set seeds for reproducibility\n",
    "random.seed(42)\n",
    "np.random.seed(42)\n",
    "\n",
    "# Ensure directories exist\n",
    "os.makedirs('../data/resumes', exist_ok=True)\n",
    "print(\"Directories verified!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Templates & Dictionaries\n",
    "\n",
    "We define candidate skills, companies, educational institutions, degrees, roles, and project templates. We explicitly inject the required skill synonyms:\n",
    "- `JavaScript` vs `JS`\n",
    "- `Machine Learning` vs `ML`\n",
    "- `PostgreSQL` vs `Postgres`\n",
    "- `C#` vs `C Sharp` vs `.NET`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "ROLES = [\n",
    "    \"Software Engineer\", \"Frontend Developer\", \"Backend Developer\", \n",
    "    \"Data Scientist\", \"Machine Learning Engineer\", \"DevOps Engineer\", \n",
    "    \"Product Manager\", \"QA Engineer\"\n",
    "]\n",
    "\n",
    "COMPANIES = [\n",
    "    \"Google\", \"Microsoft\", \"Meta\", \"Amazon\", \"Netflix\", \"Apple\", \n",
    "    \"Stripe\", \"Uber\", \"Airbnb\", \"Salesforce\", \"Atlassian\", \"Slack\", \n",
    "    \"ABC Technologies\", \"XYZ Solutions\", \"Innovate Labs\", \"Global Tech\"\n",
    "]\n",
    "\n",
    "UNIVERSITIES = [\n",
    "    \"Stanford University\", \"MIT\", \"UC Berkeley\", \"Carnegie Mellon University\", \n",
    "    \"Georgia Tech\", \"Caltech\", \"University of Washington\", \"University of Michigan\",\n",
    "    \"State University\", \"City College\", \"Ivy League University\", \"Tech Institute\"\n",
    "]\n",
    "\n",
    "DEGREES = [\n",
    "    (\"Bachelor of Science\", \"Computer Science\", 1.0),\n",
    "    (\"Master of Science\", \"Computer Science\", 1.0),\n",
    "    (\"Bachelor of Science\", \"Information Technology\", 0.9),\n",
    "    (\"Master of Science\", \"Data Science\", 0.95),\n",
    "    (\"Doctor of Philosophy\", \"Computer Science\", 1.0),\n",
    "    (\"Bachelor of Engineering\", \"Electrical Engineering\", 0.8),\n",
    "    (\"Master of Business Administration\", \"Product Management\", 0.7),\n",
    "    (\"Bachelor of Arts\", \"History\", 0.2), # Unrelated for checking education match\n",
    "]\n",
    "\n",
    "SKILLS_POOL = {\n",
    "    \"Software Engineer\": [\n",
    "        [\"JavaScript\", \"JS\"], [\"Python\", \"Python3\"], [\"C#\", \"C Sharp\", \".NET\"], \n",
    "        [\"Java\"], [\"PostgreSQL\", \"Postgres\"], [\"SQL\", \"MySQL\"], [\"Docker\"], \n",
    "        [\"AWS\"], [\"Git\"], [\"REST APIs\"], [\"Data Structures\"], [\"Algorithms\"]\n",
    "    ],\n",
    "    \"Frontend Developer\": [\n",
    "        [\"JavaScript\", \"JS\"], [\"React\"], [\"HTML5\"], [\"CSS3\"], [\"Sass\"], \n",
    "        [\"Vue\"], [\"TypeScript\", \"TS\"], [\"Webpack\"], [\"Bootstrap\"], [\"Tailwind\"]\n",
    "    ],\n",
    "    \"Backend Developer\": [\n",
    "        [\"Python\"], [\"Node.js\", \"Node\"], [\"Java\"], [\"Go\", \"Golang\"], \n",
    "        [\"PostgreSQL\", \"Postgres\"], [\"MongoDB\"], [\"Redis\"], [\"Docker\"], \n",
    "        [\"Kubernetes\"], [\"AWS\"], [\"REST APIs\"], [\"GraphQL\"], [\"C#\", \"C Sharp\", \".NET\"]\n",
    "    ],\n",
    "    \"Data Scientist\": [\n",
    "        [\"Python\"], [\"R\"], [\"SQL\"], [\"Machine Learning\", \"ML\"], \n",
    "        [\"Deep Learning\"], [\"Pandas\"], [\"NumPy\"], [\"Scikit-Learn\", \"Sklearn\"], \n",
    "        [\"PostgreSQL\", \"Postgres\"], [\"Tableau\"], [\"Data Analysis\"], [\"Statistics\"]\n",
    "    ],\n",
    "    \"Machine Learning Engineer\": [\n",
    "        [\"Python\"], [\"Machine Learning\", \"ML\"], [\"Deep Learning\"], \n",
    "        [\"PyTorch\"], [\"TensorFlow\"], [\"NLP\"], [\"Computer Vision\"], \n",
    "        [\"Scikit-Learn\", \"Sklearn\"], [\"Docker\"], [\"MLflow\"], [\"AWS\"]\n",
    "    ],\n",
    "    \"DevOps Engineer\": [\n",
    "        [\"Docker\"], [\"Kubernetes\"], [\"AWS\"], [\"Terraform\"], [\"Ansible\"], \n",
    "        [\"Linux\"], [\"Bash\"], [\"CI/CD\"], [\"Jenkins\"], [\"Python\"], [\"Prometheus\"]\n",
    "    ],\n",
    "    \"Product Manager\": [\n",
    "        [\"Product Roadmap\"], [\"Agile\"], [\"Scrum\"], [\"Jira\"], [\"SQL\"], \n",
    "        [\"A/B Testing\"], [\"Market Analysis\"], [\"User Stories\"], [\"Strategy\"]\n",
    "    ],\n",
    "    \"QA Engineer\": [\n",
    "        [\"Selenium\"], [\"Playwright\"], [\"Python\"], [\"JavaScript\", \"JS\"], \n",
    "        [\"SQL\"], [\"Manual Testing\"], [\"API Testing\"], [\"Postman\"], [\"CI/CD\"]\n",
    "    ]\n",
    "}\n",
    "\n",
    "PROJECT_TEMPLATES = {\n",
    "    \"Software Engineer\": [\n",
    "        \"Developed a distributed key-value store using C# and .NET with high throughput.\",\n",
    "        \"Built a responsive web platform utilizing JavaScript (JS) and React on the frontend.\",\n",
    "        \"Designed and query-optimized an enterprise-scale relational database using PostgreSQL (Postgres).\",\n",
    "        \"Containerized multi-service web applications using Docker and deployed on AWS.\"\n",
    "    ],\n",
    "    \"Frontend Developer\": [\n",
    "        \"Designed a modular e-commerce dashboard using React, Tailwind CSS, and TypeScript.\",\n",
    "        \"Re-architected client-facing web application with modern JavaScript (JS) reducing page loads.\",\n",
    "        \"Built a collaborative drag-and-drop workspace using HTML5, CSS3, and Sass.\",\n",
    "        \"Developed a responsive components library styled with Bootstrap and integrated with Vue.\"\n",
    "    ],\n",
    "    \"Backend Developer\": [\n",
    "        \"Developed high-performance microservices in Go and Python communicating via REST and gRPC.\",\n",
    "        \"Designed database schema for an ERP system on PostgreSQL (Postgres), reducing query times.\",\n",
    "        \"Built a real-time messaging gateway utilizing Node.js, WebSockets, and Redis cache.\",\n",
    "        \"Implemented enterprise authentication APIs using ASP.NET Core in C Sharp (.NET).\"\n",
    "    ],\n",
    "    \"Data Scientist\": [\n",
    "        \"Built a customer churn predictive model using Machine Learning (ML) and XGBoost on tabular data.\",\n",
    "        \"Performed statistical analysis on huge marketing datasets with Pandas, NumPy, and Tableau.\",\n",
    "        \"Developed a recommendation system based on natural language reviews and Pandas.\",\n",
    "        \"Analyzed user search behavior datasets stored in PostgreSQL (Postgres) to extract key patterns.\"\n",
    "    ],\n",
    "    \"Machine Learning Engineer\": [\n",
    "        \"Trained and fine-tuned a BERT-based NLP model using PyTorch for sentiment classification.\",\n",
    "        \"Deployed a computer vision pipeline with TensorFlow and OpenCV for object detection.\",\n",
    "        \"Built an automated end-to-end Machine Learning (ML) retraining pipeline using MLflow.\",\n",
    "        \"Designed large-scale similarity search index using Sentence Transformers on AWS.\"\n",
    "    ],\n",
    "    \"DevOps Engineer\": [\n",
    "        \"Designed infrastructure-as-code deployments using Terraform to manage AWS resources.\",\n",
    "        \"Orchestrated auto-scaling Kubernetes clusters with Prometheus monitoring dashboard.\",\n",
    "        \"Established secure CI/CD build pipelines using GitHub Actions and Docker.\",\n",
    "        \"Automated system configuration and package management using Ansible playbooks.\"\n",
    "    ],\n",
    "    \"Product Manager\": [\n",
    "        \"Launched a mobile app product roadmap driving user growth and engagement metrics.\",\n",
    "        \"Managed agile sprint backlogs and product requirements in Jira across 3 cross-functional teams.\",\n",
    "        \"Designed and executed user retention A/B testing campaigns, parsing telemetry with SQL.\",\n",
    "        \"Conducted target market analysis and defined functional user stories for beta launch.\"\n",
    "    ],\n",
    "    \"QA Engineer\": [\n",
    "        \"Automated web application testing using Selenium WebDriver and Python pytest.\",\n",
    "        \"Constructed end-to-end regression testing suites using Playwright and JavaScript (JS).\",\n",
    "        \"Executed manual and automated API validation tests with Postman and custom scripts.\",\n",
    "        \"Integrated test automation scripts into GitLab CI/CD pipeline for pull request validations.\"\n",
    "    ]\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Generating Resumes\n",
    "\n",
    "We will generate at least **200 resumes** as text-based PDFs. We will write the files to `../data/resumes/resume_xxx.pdf`. We will ensure that section headers are explicitly and correctly placed to follow the parsing rules. We will also include a few invalid/scanned resumes to test boundaries."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def pick_random_skills(role, count=5):\n",
    "    selected = []\n",
    "    role_pool = SKILLS_POOL[role]\n",
    "    chosen_lists = random.sample(role_pool, min(count, len(role_pool)))\n",
    "    for cl in chosen_lists:\n",
    "        # randomly select one synonym form\n",
    "        selected.append(random.choice(cl))\n",
    "    return selected\n",
    "\n",
    "def generate_resume_text(index, role):\n",
    "    # Select header names randomly from the valid headers to ensure robustness\n",
    "    skills_headers = [\"Skills\", \"Technical Skills\", \"Core Skills\"]\n",
    "    exp_headers = [\"Experience\", \"Work Experience\", \"Professional Experience\", \"Internships\"]\n",
    "    proj_headers = [\"Projects\", \"Academic Projects\", \"Personal Projects\"]\n",
    "    edu_headers = [\"Education\", \"Academic Background\"]\n",
    "\n",
    "    # Generate Sections\n",
    "    skills = pick_random_skills(role, count=random.randint(6, 9))\n",
    "    \n",
    "    # Experience Validation Rule test:\n",
    "    # 95% of resumes will have valid experience (Role, Company, Duration)\n",
    "    # 5% will have invalid/missing data to verify parser\n",
    "    has_valid_exp = random.random() < 0.95\n",
    "    exp_entries = []\n",
    "    if has_valid_exp:\n",
    "        for _ in range(random.randint(1, 2)):\n",
    "            comp = random.choice(COMPANIES)\n",
    "            dur = f\"{random.choice(['January', 'June', 'September'])} {random.randint(2020, 2023)} - {random.choice(['August', 'December'])} {random.randint(2024, 2025)}\"\n",
    "            exp_role = f\"{random.choice(['Senior', 'Junior', 'Associate', 'Lead', ''])} {role}\".strip()\n",
    "            exp_entries.append(f\"{exp_role}\\n{comp}\\n{dur}\\n- Designed and implemented major components.\\n- Collaborated with cross-functional teams to deliver scale products.\")\n",
    "    else:\n",
    "        # Invalid experience\n",
    "        exp_entries.append(\"Worked as a general programmer on multiple client sites doing general tasks without specified duration.\")\n",
    "\n",
    "    # Projects\n",
    "    proj_entries = []\n",
    "    proj_templates = PROJECT_TEMPLATES[role]\n",
    "    chosen_projs = random.sample(proj_templates, min(2, len(proj_templates)))\n",
    "    for p in chosen_projs:\n",
    "        proj_title = f\"{role.replace(' ', '')} {random.randint(100, 999)}\"\n",
    "        proj_entries.append(f\"{proj_title}\\n{p}\")\n",
    "        \n",
    "    # Education\n",
    "    edu_choice = random.choice(DEGREES)\n",
    "    degree, field, _ = edu_choice\n",
    "    uni = random.choice(UNIVERSITIES)\n",
    "    edu_year = random.randint(2015, 2024)\n",
    "    edu_text = f\"{degree} in {field}\\n{uni}, {edu_year}\"\n",
    "\n",
    "    resume_dict = {\n",
    "        \"name\": f\"Candidate_{index}\",\n",
    "        \"target_role\": role,\n",
    "        \"skills_header\": random.choice(skills_headers),\n",
    "        \"skills\": \", \".join(skills),\n",
    "        \"exp_header\": random.choice(exp_headers),\n",
    "        \"experience\": \"\\n\\n\".join(exp_entries),\n",
    "        \"proj_header\": random.choice(proj_headers),\n",
    "        \"projects\": \"\\n\\n\".join(proj_entries),\n",
    "        \"edu_header\": random.choice(edu_headers),\n",
    "        \"education\": edu_text\n",
    "    }\n",
    "    return resume_dict\n",
    "\n",
    "resumes_data = []\n",
    "for i in range(1, 201):\n",
    "    role = random.choice(ROLES)\n",
    "    resumes_data.append(generate_resume_text(i, role))\n",
    "\n",
    "# Add 5 image-only/scanned style empty resumes to verify rejection later\n",
    "for i in range(201, 206):\n",
    "    resumes_data.append({\n",
    "        \"name\": f\"Scanned_Candidate_{i}\",\n",
    "        \"target_role\": \"Software Engineer\",\n",
    "        \"skills_header\": \"Skills\",\n",
    "        \"skills\": \"\", # empty content simulates scanned/empty text extraction\n",
    "        \"exp_header\": \"Experience\",\n",
    "        \"experience\": \"\",\n",
    "        \"proj_header\": \"Projects\",\n",
    "        \"projects\": \"\",\n",
    "        \"edu_header\": \"Education\",\n",
    "        \"education\": \"\"\n",
    "    })\n",
    "\n",
    "print(f\"Generated data profiles for {len(resumes_data)} candidates.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 2.1 Generating PDFs using ReportLab\n",
    "We now compile the candidate profiles into physical PDF documents in `../data/resumes/`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "styles = getSampleStyleSheet()\n",
    "normal_style = styles['Normal']\n",
    "title_style = ParagraphStyle(\n",
    "    'TitleStyle',\n",
    "    parent=styles['Heading1'],\n",
    "    fontSize=18,\n",
    "    spaceAfter=12\n",
    ")\n",
    "h2_style = ParagraphStyle(\n",
    "    'H2Style',\n",
    "    parent=styles['Heading2'],\n",
    "    fontSize=14,\n",
    "    spaceBefore=10,\n",
    "    spaceAfter=6\n",
    ")\n",
    "\n",
    "def build_pdf(resume, file_path):\n",
    "    doc = SimpleDocTemplate(file_path, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)\n",
    "    story = []\n",
    "    \n",
    "    # Name & Contact Info\n",
    "    story.append(Paragraph(resume[\"name\"], title_style))\n",
    "    story.append(Paragraph(f\"Email: {resume['name'].lower()}@example.com | Target Role: {resume['target_role']}\", normal_style))\n",
    "    story.append(Spacer(1, 15))\n",
    "    \n",
    "    # If it is a mock scanned resume, do not write sections to keep extracted text empty\n",
    "    if \"Scanned\" in resume[\"name\"]:\n",
    "        # Write empty or trivial drawing canvas, no text blocks\n",
    "        story.append(Spacer(1, 10))\n",
    "        doc.build(story)\n",
    "        return\n",
    "\n",
    "    # Skills Section\n",
    "    story.append(Paragraph(resume[\"skills_header\"], h2_style))\n",
    "    story.append(Paragraph(resume[\"skills\"], normal_style))\n",
    "    story.append(Spacer(1, 10))\n",
    "    \n",
    "    # Experience Section\n",
    "    story.append(Paragraph(resume[\"exp_header\"], h2_style))\n",
    "    for line in resume[\"experience\"].split(\"\\n\"):\n",
    "        story.append(Paragraph(line, normal_style))\n",
    "    story.append(Spacer(1, 10))\n",
    "\n",
    "    # Projects Section\n",
    "    story.append(Paragraph(resume[\"proj_header\"], h2_style))\n",
    "    for line in resume[\"projects\"].split(\"\\n\"):\n",
    "        story.append(Paragraph(line, normal_style))\n",
    "    story.append(Spacer(1, 10))\n",
    "    \n",
    "    # Education Section\n",
    "    story.append(Paragraph(resume[\"edu_header\"], h2_style))\n",
    "    for line in resume[\"education\"].split(\"\\n\"):\n",
    "        story.append(Paragraph(line, normal_style))\n",
    "        \n",
    "    doc.build(story)\n",
    "\n",
    "for idx, res in enumerate(resumes_data):\n",
    "    path = f\"../data/resumes/resume_{idx+1:03d}.pdf\"\n",
    "    build_pdf(res, path)\n",
    "\n",
    "print(\"All 205 PDFs constructed successfully in ../data/resumes/\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Generating Job Descriptions\n",
    "\n",
    "We need to generate at least **50 job descriptions**. We will save these to a JSON database file `../data/jobs.json`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "jobs_data = []\n",
    "for i in range(1, 51):\n",
    "    role = random.choice(ROLES)\n",
    "    # select required skills from pool\n",
    "    required_skills = [random.choice(sk) for sk in random.sample(SKILLS_POOL[role], min(5, len(SKILLS_POOL[role])))]\n",
    "    \n",
    "    # create experience requirements\n",
    "    min_years = random.choice([2, 3, 5])\n",
    "    exp_req = f\"{min_years}+ years of experience working as a {role} or similar position.\"\n",
    "    \n",
    "    # project requirements\n",
    "    proj_templates = PROJECT_TEMPLATES[role]\n",
    "    proj_req = f\"Looking for candidates who have experience in projects such as: {random.choice(proj_templates)}\"\n",
    "    \n",
    "    # education requirements\n",
    "    edu_choice = random.choice(DEGREES[:6]) # exclude unrelated degree for jobs\n",
    "    degree, field, _ = edu_choice\n",
    "    edu_req = f\"{degree} in {field} or equivalent technical experience.\"\n",
    "    \n",
    "    job = {\n",
    "        \"id\": f\"JOB_{i:02d}\",\n",
    "        \"title\": f\"{role} - Category {random.choice(['A', 'B', 'C'])}\",\n",
    "        \"role\": role,\n",
    "        \"required_skills\": required_skills,\n",
    "        \"experience_requirements\": {\n",
    "            \"years\": min_years,\n",
    "            \"role_match\": role,\n",
    "            \"description\": exp_req\n",
    "        },\n",
    "        \"project_requirements\": {\n",
    "            \"description\": proj_req\n",
    "        },\n",
    "        \"education_requirements\": {\n",
    "            \"degree\": degree,\n",
    "            \"field\": field,\n",
    "            \"description\": edu_req\n",
    "        }\n",
    "    }\n",
    "    jobs_data.append(job)\n",
    "\n",
    "with open('../data/jobs.json', 'w') as f:\n",
    "    json.dump(jobs_data, f, indent=2)\n",
    "\n",
    "print(f\"Saved {len(jobs_data)} job descriptions to ../data/jobs.json\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Fine-Tuning Training Dataset Generation\n",
    "\n",
    "We need to train our Sentence Transformers model to recognize the semantic relationships between resumes and jobs. We will construct a synthetic dataset of triplets (Anchor, Positive, Negative) or query-document scores to perform fine-tuning. Let's create a dataset mapping matching resumes (positive) vs non-matching resumes (negative) for each job."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "training_pairs = []\n",
    "evaluation_pairs = []\n",
    "\n",
    "# Create training pairs\n",
    "# We will use the first 40 jobs and 150 resumes for training,\n",
    "# and the remaining 10 jobs and 50 resumes for evaluation.\n",
    "train_jobs = jobs_data[:40]\n",
    "eval_jobs = jobs_data[40:]\n",
    "\n",
    "train_resumes = resumes_data[:150]\n",
    "eval_resumes = resumes_data[150:200] # exclude mock scanned resumes\n",
    "\n",
    "def create_pairs(jobs_subset, resumes_subset, file_prefix):\n",
    "    pairs = []\n",
    "    for job in jobs_subset:\n",
    "        job_text = f\"Job Title: {job['title']}\\nRole: {job['role']}\\nSkills: {', '.join(job['required_skills'])}\\nProjects: {job['project_requirements']['description']}\\nEducation: {job['education_requirements']['description']}\"\n",
    "        for resume in resumes_subset:\n",
    "            resume_text = f\"Resume of {resume['name']}\\nSkills: {resume['skills']}\\nExperience: {resume['experience']}\\nProjects: {resume['projects']}\\nEducation: {resume['education']}\"\n",
    "            \n",
    "            # Determine relevance\n",
    "            # Score 1.0 if role matches, 0.0 otherwise\n",
    "            label = 1.0 if resume['target_role'] == job['role'] else 0.0\n",
    "            pairs.append({\n",
    "                \"job\": job_text,\n",
    "                \"resume\": resume_text,\n",
    "                \"label\": label\n",
    "            })\n",
    "    return pairs\n",
    "\n",
    "train_pairs_list = create_pairs(train_jobs, train_resumes, 'train')\n",
    "eval_pairs_list = create_pairs(eval_jobs, eval_resumes, 'eval')\n",
    "\n",
    "with open('../data/train_dataset.json', 'w') as f:\n",
    "    json.dump(train_pairs_list, f, indent=2)\n",
    "\n",
    "with open('../data/eval_dataset.json', 'w') as f:\n",
    "    json.dump(eval_pairs_list, f, indent=2)\n",
    "\n",
    "print(f\"Created {len(train_pairs_list)} training pairs and {len(eval_pairs_list)} evaluation pairs.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Dataset Visualizations\n",
    "\n",
    "Let's visualize the synthetic data distribution to verify balancing."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Plot distribution of jobs and resumes by role\n",
    "job_roles = [j['role'] for j in jobs_data]\n",
    "resume_roles = [r['target_role'] for r in resumes_data if 'Scanned' not in r['name']]\n",
    "\n",
    "plt.figure(figsize=(12, 5))\n",
    "\n",
    "plt.subplot(1, 2, 1)\n",
    "sns.countplot(y=job_roles, order=ROLES, palette='viridis')\n",
    "plt.title('Job Descriptions per Role')\n",
    "plt.xlabel('Count')\n",
    "\n",
    "plt.subplot(1, 2, 2)\n",
    "sns.countplot(y=resume_roles, order=ROLES, palette='magma')\n",
    "plt.title('Resumes per Role')\n",
    "plt.xlabel('Count')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('../app/static/charts/dataset_distribution.png')\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

with open('notebooks/data_preprocessing.ipynb', 'w') as f:
    json.dump(notebook, f, indent=2)
print("data_preprocessing.ipynb written!")
